create table asignatura_limpia
(
    idAsignatura int  null,
    codigo       text null,
    nombre       text null
);

INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (5, 'Utpldg001', 'Prototipado');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (6, 'Utplrl001', 'Ingenieria web');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (7, 'Utplrc001', 'Procesos de ingenieria de software');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (8, 'Utplfc001', 'Computacion y sociedad');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (9, 'Utpldi001', 'Estructuras de datos');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (10, 'Utplgr001', 'Computacion aplicada a la ingenieria');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (11, 'Utpljc001', 'Sistemas basados en conocimientos');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (12, 'Utplfs001', 'Innovacion en sistemas intensivos en software');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (13, 'Utplrl002', 'Desarrollo web');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (14, 'Utplcc001', 'Fisica basica');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (15, 'Utplcc002', 'Fluid mechanics');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (16, 'Utplcc003', 'Algebra lineal');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (17, 'Utplkv001', 'Relaciones publicas');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (18, 'Utplav001', 'Sociologia (mad)');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (19, 'Utplav002', 'Sociologia (presencial)');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (20, 'Utplav003', 'Metodos y tecnicas de investigacion (mad)');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (21, 'Utplav004', 'Tecnicas cualitativas (posgrado)');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (22, 'Utplja001', 'Semiotica  100-red');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (23, 'Utplja002', 'Radio  100-ects');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (24, 'Utplja003', 'Radio  101-red');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (25, 'Utplja004', 'Radio  100-red');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (26, 'Utplja005', 'Radio-cce  ects-100');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (27, 'Utplja006', 'Elab. plan rrpp  100-ects');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (28, 'Utplja007', 'Gp 4.1  tt1');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (29, 'Utplja008', 'Semiotica presencial  a');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (30, 'Utplmp001', 'Generos periodn¬sticos');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (31, 'Utplas001', 'Emprendimiento');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (32, 'Utplve001', 'Practicum 1 de pedagogia de los idiomas nacionales y extranjeros');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (33, 'Utpljy001', 'Comunicacion organizacional');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (34, 'Utplko001', 'Practicum ii');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (35, 'Utplko002', 'Periodismo de investigacion');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (36, 'Utplva001', 'Asesoria y media training');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (37, 'Utplav002', 'Marca personal e imagen');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (38, 'Utplhy001', 'Radio');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (39, 'Utplhy002', 'Radio y television para rrpp');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (40, 'Utplhy003', 'Epistemilogia de la cultura digital');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (41, 'Utplml001', 'G.p.4.2 presencia');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (42, 'Utplml002', 'Administracion distancia');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (43, 'Utpljo001', 'Microeconomia iii');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (44, 'Utpljo002', 'Economia de la empresa y mercado');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (45, 'Utplde001', 'Economia de la empresa y mercado 1');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (46, 'Utplde002', 'Economia de la empresa y mercado 2');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (47, 'Utplpa001', 'Administracion estrategica');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (48, 'Utpldr001', 'Tendencias de la comunicacion');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (49, 'Utpljcm001', 'Television');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (50, 'Utplamb001', 'Teoria de la comunicacion  educomunicacion');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (51, 'Utplde003', 'Principios de microeconomia 1');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (52, 'Utplde004', 'Principios de microeconomia 2');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (53, 'Utpllvp001', 'Derecho civil personas');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (54, 'Utplmvm001', 'Antenas a');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (55, 'Utplmvm002', 'Antenas b');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (56, 'Utpllac001', 'Dibujo para ingenieria c');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (57, 'Utpllac002', 'Dibujo para ingenieria d');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (58, 'Utpldap001', 'Farmacologia');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (59, 'Utplcml001', 'Gestion productiva 3.1');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (60, 'Utplcml002', 'Enfoque de genero en la investigacion');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (61, 'Utplcml003', 'Practicum 1');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (62, 'Utplmea001', 'Asesoria en el manejo del eva');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (63, 'Utplajp001', 'Derecho mercantil');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (64, 'Utplajp002', 'Derecho societario');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (65, 'Glgjjb001', 'Lengua y literatura');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (66, 'Glgjjb002', 'Matematicas');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (67, 'Glgjjb003', 'Ciencias naturales');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (68, 'Glgjjb004', 'Estudios sociales');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (69, 'Utplcjv001', 'Estadistica c');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (70, 'Utplcjv002', 'Pavimentos a');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (71, 'Utplcjv003', 'Pavimentos b');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (72, 'Utplgpc001', 'Enfermeria familiar y comunitaria');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (73, 'Utplgpc002', 'Salud comunitaria en internado rotativo');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (74, 'Utplmap001', 'Fundamentos de ingenieria de software');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (75, 'Utplmp002', 'Gestion de tecnologias de la informacion');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (76, 'Utpllvt001', 'Practicum 3');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (77, 'Utpldr002', 'Ciberperiodismo tendencias actuales');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (78, 'Utpl2021001', 'Fisica basica');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (79, 'Utpl2021002', 'Fundamentos matematicos');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (80, 'Utpl2021003', 'Algebra lineal');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (81, 'Utplcjv004', 'Estadistica  a oct 20 - feb 21');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (82, 'Utplcjv005', 'Estadistica b oct 20 - feb 21');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (83, 'Utplcjv006', 'Transito a oct 20 - feb 21');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (84, 'Utplcjv007', 'Topografia ii - c oct 20 - feb 21');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (85, 'Utplrl003', 'Ing. web a oct 20 - feb 21');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (86, 'Utploct20feb2101', 'Fotografia 1 oct20-feb21');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (87, 'Utploct20feb2102', 'Diseno iii  oct20-feb21');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (88, 'Utploct20feb2103', 'Arte digital 2d  oct20-feb21');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (89, 'Utploct20feb2101', 'Escultura  oct20-feb21');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (90, 'Utploct20feb2102', 'Introduccion a la historia del arte  oct20-feb21');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (91, 'Utploct20feb2101', 'Dibujo anatomico  oct20-feb21');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (92, 'Utploct20feb2102', 'G.p 3.1  oct20-feb21');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (93, 'Utploct20feb2101', 'Dibujo tecnico  oct20-feb21');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (94, 'Utploct20feb2102', 'G.p 4.1  oct20-feb21');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (95, 'Utploct20feb2101', 'Evento educameter');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (96, 'Utploct20feb2102', 'Fundamentos de tecnologias de la informacion oct20-feb21');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (97, 'Utploct20feb2101', 'Educomunicacion ects oct20-feb21');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (98, 'Utploct20feb2101', 'Teoria de la comunicacion ects oct20-feb21');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (99, 'Utploct20feb2101', 'Pasantias preprofesionales y de vinculacion con la colectividad');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (100, 'Utploct20feb2101', 'Pasantias preprofesionales practicum 3.2');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (101, 'Utplabria-gos21', 'Diseno de pavimentos a');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (102, 'Utplabria-gos21', 'Estadistica (geologia)');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (103, 'Utplabria-gos21', 'Microeconomia aplicada mad');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (104, 'Utplabria-gos21', 'Economia de la migracion mp');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (105, 'Utplabria-gos21', 'Asesoria del sistema maestria mad');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (106, 'Utplabria-gos21', 'Tendencias de la comunicacion');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (107, 'Utplabria-gos21', 'Television');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (108, 'Utplabria-gos21', 'Educomunicacion');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (109, 'Utplabria-gos21', 'Microeconomia iii  (ects) ab-ag21');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (110, 'Utplabria-gos21', 'Economia de la empresa y mercado (rediseno) ab-ag21');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (111, 'Utplabria-gos21', 'Teoria microeconomica');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (112, 'Utplabria-gos21', 'Teoria microeconomica 108 red');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (113, 'Utplabria-gos21', 'Taller de creacion artist. 1 (4c)');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (114, 'Utplabria-gos21', 'Ilustracion analogica y digital');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (115, 'Utplabria-gos21', 'Circuito del arte en el ecuador');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (116, 'Utplabria-gos21', 'Esculto-ceramica 1');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (117, 'Utplabria-gos21', 'Dibujo y modelado 1');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (118, 'Utplabria-gos21', 'Arte y espacio publico');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (119, 'Utplabria-gos21', 'Reproduccion analogica y digital');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (120, 'Utplabria-gos21', 'Practicum 1');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (121, 'Utplabria-gos21', 'Historia del arte v');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (122, 'Utplabria-gos21', 'Historia del arte vii');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (123, 'Utplabria-gos21', 'Taller de creacion  artistica 3');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (124, 'Utplabria-gos21', 'Gestion productiva  3.1');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (125, 'Utplabria-gos21', 'Fotografia artistica');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (126, 'Utplabria-gos21', 'Diseno en prensa');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (127, 'Utplabria-gos21', 'Dibujo artistico iv');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (128, 'Utplabria-gos21', 'Ilustracion animada');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (129, 'Utplabria-gos21', 'Arte y cultura');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (130, 'Utploct21-feb22', 'Construccion de carreteras ii');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (131, 'Utploct21-feb22', 'Presupuesto y control de obras');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (132, 'Utploct21-feb22', 'Tecnologia de los materiales');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (133, 'Utploct21-feb22', 'Herramientas de diseno digital');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (134, 'Utploct21-feb22', 'Teorias de la comunicacion i');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (135, 'Utploct21-feb22', 'Contabilidad agraria oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (136, 'Utploct21-feb22', 'Principios de auditoria oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (137, 'Utploct21-feb22', 'Auditoria oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (138, 'Utploct21-feb22', 'Teoria de la comunicacion 100red oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (139, 'Utploct21-feb22', 'Teoria de la comunicacion 102red oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (140, 'Utploct21-feb22', 'Entrevista y evaluacion psicologica oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (141, 'Utploct21-feb22', 'Derecho a la comunicacion y la informacion oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (142, 'Utploct21-feb22', 'Semiotica oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (143, 'Utploct21-feb22', 'Teoria de la imagen oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (144, 'Utploct21-feb22', 'Cine oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (145, 'Utploct21-feb22', 'Disen‘o de productos turisticos oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (146, 'Utploct21-feb22', 'Planificacion de destinos turisticos oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (147, 'Utploct21-feb22', 'Competitividad de destinos turisticos oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (148, 'Utploct21-feb22', 'Gestion del patrimonio cultural oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (149, 'Utploct21-feb22', 'Practicum 1 oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (150, 'Utploct21-feb22', 'Patrimonio natural y biodiversidad oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (151, 'Utploct21-feb22', 'Gestion productiva gp 3 oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (152, 'Utploct21-feb22', 'Examen complexivo oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (153, 'Utploct21-feb22', 'Tendencias de la comunicacion oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (154, 'Utploct21-feb22', 'Epidemiologia y salud publica oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (155, 'Utploct21-feb22', 'Fundamentos de bases de datos oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (156, 'Utploct21-feb22', 'Fundamentos de base de datos oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (157, 'Utploct21-feb22', 'Plataformas web oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (158, 'Utploct21-feb22', 'Economia internacional oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (159, 'Utploct21-feb22', 'Dibujo tecnico oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (160, 'Utploct21-feb22', 'Herramientas digitales oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (161, 'Utploct21-feb22', 'Dibujo e ideacion oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (162, 'Utploct21-feb22', 'Dibujo e ideacion loct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (163, 'Utploct21-feb22', 'Dibujo e ideacion soct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (164, 'Utploct21-feb22', 'Algebra lineal oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (165, 'Utploct21-feb22', 'Matematica basica oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (166, 'Utploct21-feb22', 'Radio y nuevas tecnologias oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (167, 'Utploct21-feb22', 'Algebra lineal oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (168, 'Utploct21-feb22', 'Algebra lineal noct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (169, 'Utploct21-feb22', 'Economia ambiental y de los recursos naturales oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (170, 'Utploct21-feb22', 'Microeconomia oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (171, 'Utploct21-feb22', 'Contaminacion y remediacion de suelos oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (172, 'Utploct21-feb22', 'Itinerario 2 a. mineria sustentable oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (173, 'Utploct21-feb22', 'Practicum 3 pasantias pre-profesionales oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (174, 'Utploct21-feb22', 'Microeconomia aplicada oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (175, 'Utploct21-feb22', 'Principios de microeconomia oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (176, 'Utploct21-feb22', 'Economia de la empresa y mercado oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (177, 'Utploct21-feb22', 'Microeconomia aplicada joct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (178, 'Utploct21-feb22', 'Gp 4.1 proyecto de fin de carrera oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (179, 'Utploct21-feb22', 'Comunicacion y argumentacion en la era digital oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (180, 'Utploct21-feb22', 'Comunicacion y argumentacion en la era digital coct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (181, 'Utploct21-feb22', 'Comunicacion y argumentacion en la era digital doct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (182, 'Utploct21-feb22', 'Teoria de la comunicacion oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (183, 'Utploct21-feb22', 'Pasantias pre-profesinales (practicum 3.2) oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (184, 'Utploct21-feb22', 'Gestion del curriculo para la educacion basica oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (185, 'Utploct21-feb22', 'Neuropsicologia oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (186, 'Utploct21-feb22', 'Necesidades educativas especiales asociadas a la discapacidad ii oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (187, 'Utploct21-feb22', 'Inclusion educativa oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (188, 'Utploct21-feb22', 'Itinerario ii: methodology for teaching english for academic purposes oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (189, 'Utploct21-feb22', 'Itinerario i: methodology for teaching english to children  oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (190, 'Utploct21-feb22', 'Practicum 2 oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (191, 'Utploct21-feb22', 'Language testing oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (192, 'Utploct21-feb22', 'Practicum 2 aoct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (193, 'Utploct21-feb22', 'Practicum 2 coct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (194, 'Utploct21-feb22', 'Practicum 2 eoct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (195, 'Utploct21-feb22', 'Administracion de riesgos oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (196, 'Utploct21-feb22', 'Contabilidad financiera oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (197, 'Utploct21-feb22', 'Contabilidad financiera avanzada oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (198, 'Utploct21-feb22', 'Contabilidad de costos ii oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (199, 'Utploct21-feb22', 'Practicum 2 moct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (200, 'Utploct21-feb22', 'Psicopatologia del nin‘o y del adolescente oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (201, 'Utploct21-feb22', 'Psicopatologia del nin‘o y del adolescente eoct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (202, 'Utploct21-feb22', 'Tecnicas e instrumentos para la promocion y prevencion en diferentes contextos clinicos');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (203, 'Utploct21-feb22', 'Administracion financiera operativa oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (204, 'Utploct21-feb22', 'Finanzas iii oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (205, 'Utploct21-feb22', 'Sistemas financieros oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (206, 'Utploct21-feb22', 'Finanzas personales y empresariales oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (207, 'Utploct21-feb22', 'Gestion administrativa publica oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (208, 'Utploct21-feb22', 'Herramientas de disen‘o digital oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (209, 'Utploct21-feb22', 'Imagen digital oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (210, 'Utploct21-feb22', 'Genetica clinica y enfermedades metabolicas oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (211, 'Utploct21-feb22', 'Biologia molecular oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (212, 'Utploct21-feb22', 'Genetica clinica y patologia molecular oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (213, 'Utploct21-feb22', 'Tecnicas moleculares oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (214, 'Utploct21-feb22', 'Derecho internacional publico oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (215, 'Utploct21-feb22', 'Practicum 3 oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (216, 'Utploct21-feb22', 'Tecnologias para la innovacion educativa oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (217, 'Utploct21-feb22', 'Comunicacion organizacional oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (218, 'Utploct21-feb22', 'Radio oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (219, 'Utploct21-feb22', 'Semiotica oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (220, 'Utploct21-feb22', 'Radio y nuevas tecnologias oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (221, 'Utploct21-feb22', 'Hidraulica i eoct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (222, 'Utploct21-feb22', 'Hidraulica i hoct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (223, 'Utploct21-feb22', 'Practicum 3.2 pasantias pre-profesionales oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (224, 'Utploct21-feb22', 'Practicum 4.1 oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (225, 'Utploct21-feb22', 'Itinerario i: mecanismos de financiamiento e inversion oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (226, 'Utploct21-feb22', 'Practicum 3.1 pasantias pre-profesionales oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (227, 'Utploct21-feb22', 'Gestion productiva 3.1 oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (228, 'Utploct21-feb22', 'Aplicaciones de costos oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (229, 'Utploct21-feb22', 'Practicum 2 oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (230, 'Utploct21-feb22', 'Derecho procesal constitucional jcoct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (231, 'Utploct21-feb22', 'Derecho procesal constitucional jroct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (232, 'Utploct21-feb22', 'Derecho procesal constitucional rgoct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (233, 'Utploct21-feb22', 'Bebidas alcoholicas y no alcoholicas (mixologia) oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (234, 'Utploct21-feb22', 'Preparacion de alimentos 3 (procesamiento carnico - garde manger)oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (235, 'Utploct21-feb22', 'Analisis de alimentos aplicados al desarrollo de nuevos productos oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (237, 'Utploct21-feb22', 'Practicum 3 pasantias pre-profesionales jrmoct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (238, 'Utploct21-feb22', 'Practicum 2 jpaoct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (239, 'Utploct21-feb22', 'Quimica general oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (240, 'Utploct21-feb22', 'Biologia celular y  molecular oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (241, 'Utploct21-feb22', 'Bases biologicas oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (243, 'Utploct21-feb22', 'Metodologia de la investigacion y tecnicas de estudio oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (244, 'Utploct21-feb22', 'Zoologia oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (245, 'Utploct21-feb22', 'Practicum 1 lfoct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (246, 'Utploct21-feb22', 'Practicum 2 lgoct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (247, 'Utploct21-feb22', 'Fundamentos de redes y telecomunicaciones oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (248, 'Utploct21-feb22', 'Contabilidad agraria gioct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (249, 'Utploct21-feb22', 'Contabilidad agraria wooct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (250, 'Utploct21-feb22', 'Integrado de clinica i oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (251, 'Utploct21-feb22', 'Integrado de clinica i vvoct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (252, 'Utploct21-feb22', 'Geografia turistica oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (253, 'Utploct21-feb22', 'Tics gastronomicos oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (254, 'Utploct21-feb22', 'Derecho administrativo oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (255, 'Utploct21-feb22', 'Derecho administrativo mcoct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (256, 'Utploct21-feb22', 'Pluralismo juridico oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (257, 'Utploct21-feb22', 'Derecho administrativo sroct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (258, 'Utploct21-feb22', 'Analsis matematico univariado oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (259, 'Utploct21-feb22', 'Ecuaciones diferenciales oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (260, 'Utploct21-feb22', 'Didactica de la lengua y literatura en la educacion basica oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (261, 'Utploct21-feb22', 'Didactica de la matematica en la educacion basica oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (262, 'Utploct21-feb22', 'Didactica de las ciencias sociales en la educacion basica oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (263, 'Utploct21-feb22', 'Didactica especifica de la lengua y literatura oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (264, 'Utploct21-feb22', 'Didactica de las ciencias naturales en la educacion basica oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (265, 'Utploct21-feb22', 'Orientacion y asesoramiento psicologico oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (266, 'Utploct21-feb22', 'Orientacion y asesoramiento psicologico maoct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (267, 'Utploct21-feb22', 'Dibujo tecnico cboct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (268, 'Utploct21-feb22', 'Disen‘o en prensa oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (269, 'Utploct21-feb22', 'Taller de creacion artistica iv oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (270, 'Utploct21-feb22', 'Medicina legal oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (271, 'Utploct21-feb22', 'Fundamentos filosoficos de la medicina oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (272, 'Utploct21-feb22', 'Medicina familiar oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (273, 'Utploct21-feb22', 'Anatomiia oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (274, 'Utploct21-feb22', 'Analisis matematico univariado oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (275, 'Utploct21-feb22', 'Fundamentos matematicos oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (276, 'Utploct21-feb22', 'Fisica basica oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (277, 'Utploct21-feb22', 'Analisis matematico multivariado oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (278, 'Utploct21-feb22', 'Arquitectura y seguridad de redes oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (279, 'Utploct21-feb22', 'Administracion jroct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (280, 'Utploct21-feb22', 'Administracion lcoct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (281, 'Utploct21-feb22', 'Gestion productiva 4.1 oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (282, 'Utploct21-feb22', 'Listening and speaking iv oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (283, 'Utploct21-feb22', 'Literatura ecuatoriana i oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (284, 'Utploct21-feb22', 'Corrientes contemporaneas de la teoria y critica literarias oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (285, 'Utploct21-feb22', 'Practicum 4.1 aroct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (286, 'Utploct21-feb22', 'English language: reading and writing ii oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (287, 'Utploct21-feb22', 'Administracion estrategica oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (288, 'Utploct21-feb22', 'Administracion estrategica mloct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (289, 'Utploct21-feb22', 'Administracion estrategica mcoct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (290, 'Utploct21-feb22', 'Administracion estrategica paoct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (291, 'Utploct21-feb22', 'Computacion y sociedad oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (292, 'Utploct21-feb22', 'Second language acquisition oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (293, 'Utploct21-feb22', 'Practicum 1: observacion y diagnostico del contexto educativo oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (294, 'Utploct21-feb22', 'Disen‘o de la comunicacion visual oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (295, 'Utploct21-feb22', 'Etica periodistica oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (296, 'Utploct21-feb22', 'Periodismo narrativo oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (297, 'Utploct21-feb22', 'Sostenibilidad empresarial  oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (298, 'Utploct21-feb22', 'Practicum 2 vaoct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (299, 'Utploct21-feb22', 'Practicum 1 zmoct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (300, 'Utploct21-feb22', 'Manejo de solidos oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (301, 'Utploct21-feb22', 'Contaminacion ambiental oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (302, 'Utploct21-feb22', 'Practicum 1 ndoct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (303, 'Utploct21-feb22', 'Quimica de los productos naturales y farmacognosia oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (304, 'Utploct21-feb22', 'Tecnicas de cultivos en celulas animales oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (305, 'Utploct21-feb22', 'Genetica molecular oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (306, 'Utploct21-feb22', 'Semiologia oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (307, 'Utploct21-feb22', 'Fisiopatologia oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (308, 'Utploct21-feb22', 'Educacion nutricional y salud alimentaria oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (309, 'Utploct21-feb22', 'Introduccion a la ciencia de los alimentos oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (310, 'Utploct21-feb22', 'Methodology for teaching english for specific purposes oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (311, 'Utploct21-feb22', 'Semantics and pragmatics oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (312, 'Utploct21-feb22', 'Theory for teaching grammar use oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (313, 'Utploct21-feb22', 'Evaluacion psicologica oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (314, 'Utploct21-feb22', 'Entrevista psicologica oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (315, 'Utploct21-feb22', 'Evaluacion psicologica mpoct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (316, 'Utploct21-feb22', 'Entrevista psicologica pboct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (317, 'Utploct21-feb22', 'Entrevista psicologica tmoct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (318, 'Utploct21-feb22', 'Practicum 3.1 oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (319, 'Utploct21-feb22', 'Practicum 3.1 lvoct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (320, 'Utploct21-feb22', 'Histologia oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (321, 'Utploct21-feb22', 'Histologia yqoct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (322, 'Utploct21-feb22', 'Gestion productiva 4.2 trabajo de titulacion');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (323, 'Utploct21-feb22', 'Gestion productiva 4.2 trabajo de titulacion oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (324, 'Utploct21-feb22', 'Fundamentos matematicos oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (325, 'Utploct21-feb22', 'Theory for teaching grammar use oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (326, 'Utploct21-feb22', 'Geologia estructural oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (327, 'Utploct21-feb22', 'Practicum 2 oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (328, 'Utploct21-feb22', 'Ingenieria web oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (329, 'Utploct21-feb22', 'Introduccion a la historia oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (330, 'Utploct21-feb22', 'Comunicacion politica oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (331, 'Utploct21-feb22', 'Itinerario i: curriculum foundations principles and issues oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (332, 'Utploct21-feb22', 'English language: reading and writing i oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (333, 'Utploct21-feb22', 'Seminario de fin de carrera oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (334, 'Utploct21-feb22', 'Seminario de fin de carrera ksoct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (335, 'Utploct21-feb22', 'Antropologia oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (336, 'Utploct21-feb22', 'Carcinogenesis oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (337, 'Utploct21-feb22', 'Gp 3.1 oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (338, 'Utploct21-feb22', 'Gp 3.2 oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (339, 'Utploct21-feb22', 'Gp 3.3 oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (340, 'Utploct21-feb22', 'Lectura y redaccion de textos academicos oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (341, 'Utploct21-feb22', 'Modulo actores y gestores del cambio');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (342, 'Utploct21-feb22', 'Introduccion de la historia del arte oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (343, 'Utploct21-feb22', 'Finanzas estrategicas oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (344, 'Utploct21-feb22', 'Contaminacion atmosferica oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (345, 'Utploct21-feb22', 'Calidad y tratamiento de agua oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (346, 'Utploct21-feb22', 'Evaluacion psicologica oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (347, 'Utploct21-feb22', 'Tecnicas e instrumentos para la promocion y prevencion en diferentes contextos clinicos');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (348, 'Utploct21-feb22', 'Procesos psicologicos basicos i');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (349, 'Utploct21-feb22', 'Cultivos celulares  oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (350, 'Utploct21-feb22', 'Bioquimica aplicada a la enfermeria oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (351, 'Utploct21-feb22', 'Bioquimica general oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (352, 'Utploct21-feb22', 'Evaluacion psicologica b oct21-feb22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (353, 'Utplabr-ago22', 'Estadistica â€“ geologia 2022');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (354, 'Utplabr-ago22', 'Dibujo para ingenieria civil â€“ 2022');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (355, 'Utplabr-ago22', 'Dibujo asistido por computador â€“ logistica â€“ 2022');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (356, 'Utplabr-ago22', 'Ingenieria web abr-ago22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (357, 'Utplabr-ago22', 'Desarrollo de plataformas moviles');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (358, 'Utplabr-ago22', 'Desarrollo web 22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (359, 'Utploct21-feb22', 'Evaluacion de riesgos mediante modelos probabilisticos');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (360, 'Utplabr-ago22', 'Hidrologia y metereologia');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (361, 'Utplabr-ago22', 'Economia de la empresa y mercado');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (362, 'Utplabr-ago22', 'Microeconomia aplicada (100)');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (363, 'Utplabr-ago22', 'Microeconomia aplicada (101)');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (364, 'Utploct22feb23', 'Pavimentos-a-oct22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (365, 'Utploct22feb23', 'Pavimentos-b-oct22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (366, 'Utploct22feb23', 'Materiales-b-oct22');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (367, 'Utploct22feb23', 'Contabilidad agraria oct22 fer23');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (368, 'Utploct22feb23', 'Principios de auditoria y auditoria i oct22 feb23');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (369, 'Utpl abr-ago 23', 'Evaluacion de riesgos mediante modelos probabilisticos abr-ago 23');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (370, 'Utpl abr-ago 23', 'Itinerario 2 mitigacion y preparacion de la respuesta: obras de infraestructura para la prevencion  abr-ago 23');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (371, 'Utpl abr-ago 23', 'Dibujo-a-abril-23');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (372, 'Utpl abr-ago 23', 'Dibujo-b-abril-23');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (373, 'Utpl abr-ago 23', 'Dibujo-c-abril-23');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (374, 'Utpl abr-ago 23', 'Desarrollo web tec abr-ago 23');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (375, 'Utpl abr-ago 23', 'Desarrollo web mad abr-ago 23');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (376, 'Utpl abr-ago 23', 'Plataformas moviles mad abr-ago 23');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (377, 'Utploct24feb25', 'Fundamentos  de contabilidad');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (378, 'Utploct24feb25', 'Principios de auditoria');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (379, 'Utploct24feb25', 'Cambio climatico y adaptacion');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (380, 'Utploct24feb25', 'Constitucionalismo y derecho procesal penal');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (381, 'Utploct24feb25', 'Derecho constitucional comparado');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (382, 'Utploct24feb25', 'Derechos humanos e interculturalidad');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (383, 'Utploct24feb25', 'Hidraulica avanzada');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (384, 'Utploct24feb25', 'Hidrologia y sostenibilidad');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (385, 'Utploct24feb25', 'Interpretacion constitucional');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (386, 'Utploct24feb25', 'La prueba y su valoracion');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (387, 'Utploct24feb25', 'Los procesos penales y recursos');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (388, 'Utploct24feb25', 'Los sujetos procesales');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (389, 'Utploct24feb25', 'Metodologia de investigacion');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (390, 'Utploct24feb25', 'Metodologia de la investigacion juridica');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (391, 'Utploct24feb25', 'Tecnologias de la informacion geografica aplicada a los recursos hidricos');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (392, 'Utploct24feb25', 'Titulacion 1 - c');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (393, 'Utploct24feb25', 'Titulacion 1 - b');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (394, 'Utploct24feb25', 'Titulacion 1 - a');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (395, 'Utploct24feb25', 'Titulacion i - a');
INSERT INTO FinalProyecto.asignatura_limpia (idAsignatura, codigo, nombre) VALUES (396, 'Utploct24feb25', 'Titulacion i - c');
